In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Garima_major_project/train.csv',encoding= 'unicode_escape')

In [4]:
df.head()

textID                                               text  \
0  cb774db0d1                I`d have responded, if I were going   
1  549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2  088c60f138                          my boss is bullying me...   
3  9642c003ef                     what interview! leave me alone   
4  358bd9e861   Sons of ****, why couldn`t they put them on t...   

                         selected_text sentiment Time of Tweet Age of User  \
0  I`d have responded, if I were going   neutral       morning        0-20   
1                             Sooo SAD  negative          noon       21-30   
2                          bullying me  negative         night       31-45   
3                       leave me alone  negative       morning       46-60   
4                        Sons of ****,  negative          noon       60-70   

       Country  Population -2020  Land Area (Km²)  Density (P/Km²)  
0  Afghanistan          38928346         652860.0               60  
1      Albania           2877797          27400.0              105  
2      Algeria          43851044        2381740.0               18  
3      Andorra             77265            470.0              164  
4       Angola          32866272        1246700.0               26

In [5]:
mydf=df[['text','sentiment']]

In [6]:
mydf.head()

text sentiment
0                I`d have responded, if I were going   neutral
1      Sooo SAD I will miss you here in San Diego!!!  negative
2                          my boss is bullying me...  negative
3                     what interview! leave me alone  negative
4   Sons of ****, why couldn`t they put them on t...  negative

In [7]:
type(mydf['text'][0])

str

In [8]:
"""import re
sentence="i have t**o play"
sentence=re.sub("[^a-zA-Z ]",'',sentence)
sentence"""

'import re\nsentence="i have t**o play"\nsentence=re.sub("[^a-zA-Z ]",\'\',sentence)\nsentence'

In [9]:
import re
for i in range(len(mydf.text)):
  mydf['text'][i]=re.sub("[^a-zA-Z ]","",str(mydf['text'][i]))

<ipython-input-9-bd6aa80d7016>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mydf['text'][i]=re.sub("[^a-zA-Z ]","",str(mydf['text'][i]))


In [10]:
mydf.head()

text sentiment
0                  Id have responded if I were going   neutral
1         Sooo SAD I will miss you here in San Diego  negative
2                             my boss is bullying me  negative
3                      what interview leave me alone  negative
4   Sons of  why couldnt they put them on the rel...  negative

In [11]:
mydf['sentiment'].value_counts()

neutral     11118
positive     8582
negative     7781
Name: sentiment, dtype: int64

In [12]:
mydf.isnull().mean()

text         0.0
sentiment    0.0
dtype: float64

In [13]:
label_map={"negative":0,"positive":2,"neutral":1}

In [14]:
mydf['labels']=mydf['sentiment'].map(label_map)

<ipython-input-14-88879a5b5024>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mydf['labels']=mydf['sentiment'].map(label_map)


In [15]:
mydf.head()

text sentiment  labels
0                  Id have responded if I were going   neutral       1
1         Sooo SAD I will miss you here in San Diego  negative       0
2                             my boss is bullying me  negative       0
3                      what interview leave me alone  negative       0
4   Sons of  why couldnt they put them on the rel...  negative       0

In [16]:
mydf.drop(labels=['sentiment'],axis=1,inplace=True)

<ipython-input-16-55a19096ad65>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mydf.drop(labels=['sentiment'],axis=1,inplace=True)


In [17]:
df1=mydf[mydf['labels']==1]
df2=mydf[mydf['labels']==2]
df0=mydf[mydf['labels']==0]


In [18]:
#because of limited colab memory take 1500 example for each label
df1.drop(df1.index[1500:],axis=0,inplace=True)
df2.drop(df2.index[1500:],axis=0,inplace=True)
df0.drop(df0.index[1500:],axis=0,inplace=True)

<ipython-input-18-e8d119f422cc>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(df1.index[1500:],axis=0,inplace=True)
<ipython-input-18-e8d119f422cc>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.index[1500:],axis=0,inplace=True)
<ipython-input-18-e8d119f422cc>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0.drop(df0.index[1500:],axis=0,inplace=True)


In [19]:
df1_train=df1.iloc[:1000]
df1_test=df1.iloc[1000:]
df2_train=df2.iloc[:1000]
df2_test=df2.iloc[1000:]
df0_train=df0.iloc[:1000]
df0_test=df0.iloc[1000:]

In [20]:
df_train=pd.concat([df2_train,df0_train,df1_train])
df_test=pd.concat([df1_test,df2_test,df0_test])

In [21]:
"""import nltk 
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('all')"""

"import nltk \nnltk.download('punkt')\nnltk.download('stopwords')\nfrom nltk.corpus import stopwords\nnltk.download('all')"

In [22]:

df_train=df_train.reset_index()
df_train.drop(labels=['index'],axis=1,inplace=True)
#for i in range(len(df_train['text'])):
 # df_train['text'][i] = [word for word in (nltk.word_tokenize(str(df_train['text'][i]))) if word not in set(stopwords.words('english'))]
    

In [23]:
df_test=df_test.reset_index()
df_test.drop(labels=['index'],axis=1,inplace=True)
#for i in range(len(df_test['text'])):
 # df_test['text'][i] = [word for word in (nltk.word_tokenize(str(df_test['text'][i]))) if word not in set(stopwords.words('english'))]
    

In [24]:
df_train.to_csv('/content/drive/MyDrive/Colab Notebooks/Garima_major_project/df_train.csv')
df_test.to_csv('/content/drive/MyDrive/Colab Notebooks/Garima_major_project/df_test.csv')

In [25]:
!pip install simpletransformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.5/250.5 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 35.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 105.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 111.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 83.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 108.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 49.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 22.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 kB 28.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB

In [26]:
from simpletransformers.classification import ClassificationModel

In [27]:
train_args={"reprocess_input_data":True,
            "fp16":False,
            "num_train_epochs":10}
model=ClassificationModel("bert","distilbert-base-uncased",num_labels=3,args=train_args)


You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.


Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing BertForSequenceClassification: ['distilbert.transformer.layer.5.ffn.lin1.weight', 'distilbert.transformer.layer.5.attention.v_lin.weight', 'distilbert.transformer.layer.3.attention.v_lin.weight', 'distilbert.transformer.layer.3.ffn.lin1.weight', 'distilbert.transformer.layer.0.attention.out_lin.bias', 'distilbert.transformer.layer.4.output_layer_norm.bias', 'distilbert.transformer.layer.3.sa_layer_norm.bias', 'distilbert.transformer.layer.0.attention.k_lin.weight', 'distilbert.transformer.layer.3.attention.out_lin.weight', 'distilbert.transformer.layer.2.attention.v_lin.bias', 'distilbert.transformer.layer.1.attention.v_lin.weight', 'distilbert.transformer.layer.2.attention.q_lin.bias', 'distilbert.transformer.layer.3.attention.q_lin.bias', 'distilbert.transformer.layer.4.attention.k_lin.bias', 'distilbert.transformer.layer.2.attention.out_lin.bias', 'distilbert.transformer.layer.4.attention

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'DistilBertTokenizer'. 
The class this function is called from is 'BertTokenizerFast'.


In [28]:
df_train['labels'].unique()

array([2, 0, 1])

In [29]:
model.train_model(df_train)

  0%|          | 0/3000 [00:00<?, ?it/s]

Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Running Epoch 0 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 1 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 2 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 3 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 4 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 5 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 6 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 7 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 8 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

Running Epoch 9 of 10:   0%|          | 0/375 [00:00<?, ?it/s]

(3750, 0.6188690934372445)

In [40]:
result=model.predict(str(df_test['text'][0]))
result

  0%|          | 0/120 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

(array([1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 0, 0,
        2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 1, 0, 1,
        1, 2, 2, 2, 0, 2, 1, 0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 0, 0, 0, 0, 2,
        1, 1, 2, 1, 2, 2, 0, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 1, 1, 0,
        1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 1, 2, 1, 1,
        1, 0, 0, 1, 2, 1, 2, 1, 1, 1]),
 array([[ 2.39743978e-001,  2.32535791e+000, -2.15861368e+000],
        [ 1.12814314e-314,  6.92638008e-310,  6.92668035e-310],
        [ 6.92638008e-310,  6.92638009e-310,  6.92638008e-310],
        [ 6.92638008e-310,  6.92638008e-310,  6.92668035e-310],
        [ 6.92638008e-310,  6.92638008e-310,  6.92638008e-310],
        [ 6.92638008e-310,  6.92638008e-310,  6.92638008e-310],
        [ 6.92638008e-310,  6.92638008e-310,  6.92638008e-310],
        [ 6.92638008e-310,  6.92668035e-310,  6.92638008e-310],
        [ 6.92638008e-310,  6.92638008e-310,  6.92668035e-310],
        [ 6.92

In [41]:
import numpy as np 
result=np.argmax(result[0])

In [42]:
df_test['text'][0]

'I hope I get the job so I can have some steady income and start eating well again All the cheap food is horrible for you'

In [43]:
result

1

In [44]:
result_map={0:"negative",2:"positive",1:"neutral"}
result_map[result]

'neutral'

In [ ]:
!pip install evaluate

In [ ]:
#from evaluate import load